name: Build on release

on:
    release:
        types: [ created ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6

            -   name: Read .nvmrc
                run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
                id: nvm

            -   name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
                uses: actions/setup-node@v6
                with:
                    node-version: "${{ steps.nvm.outputs.NVMRC }}"

            -   name: install
                run: npm ci

            -   name: build
                run: npm run build

            -   name: pack
                run: |
                    npm version "$GITHUB_REF_NAME" --no-git-tag-version
                    npm pack

            -   name: Upload build artifacts to release
                run: |
                    gh release upload "$GITHUB_REF_NAME" *.tgz --clobber
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
